# Generated by Django 6.0.3 on 2026-03-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=224)),
                ('teasers', models.FileField(blank=True, null=True, upload_to='teasers/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_alt_text', models.CharField(blank=True, max_length=220, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_alt_text', models.CharField(blank=True, max_length=220, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_alt_text', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
