# Generated by Django 6.0.3 on 2026-03-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_capsules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_capsules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='memories.capsule')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_waitlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
