# Generated by Django 6.0.3 on 2026-04-06 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_capsule_members_alter_capsule_creator_waitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_capsules', to=settings.AUTH_USER_MODEL),
        ),
    ]
