# Generated by Django 6.0.3 on 2026-03-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capsulers', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='capsules',
            field=models.ManyToManyField(related_name='memories_contributed', to='memories.capsule'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
