# Generated by Django 6.0.3 on 2026-04-06 17:13

import capsulers.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsulers', '0003_user_is_premium'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', capsulers.managers.UserManager()),
            ],
        ),
    ]
